apiVersion: v1
kind: Service
metadata:
  name: interchange-gateway
  namespace: cwb
  labels:
    app: interchange-gateway
spec:
  type: LoadBalancer
  selector:
    app: interchange-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
